language: ruby
sudo: false
cache: bundler
env:
  global:
  - AWS_REGION="ap-northeast-1"
  - secure: TjGELFHSjltyg+FC0elfHaYD3Kodvil2mFCefWHQKh50w2Y/bQm0oz7H6c8EVT84Ksz7D11rm40zCKBruBGxogxHsazFKM+BZzjkNYqwKqCsdNAX1t7zJaBu8UVJsCUvx5TG5D3+2TO3+Bg7coOokBNd8T0S0DhPuLl1GXJdberBFkJE0vlqEXyZYbvg7P0eqxLeD+KEqLQfJ6/Hc6lg83uPSe5xkp8zzzCfdJxCsVj/3tGiwbHsn7Zqd+Xyztut53SuBuFYEVdySq6l943AuSQoAr39zrA7FzMnAVm5PV05PtY4FpjvRoqgax3mNeqOYD2nwW/dFecIhUi7rYmB+KTpf9Aci/gP1ncZgF9O6PebZcGCVYaRz4FEB/sazLvZKxkkbN4vLUuHHJVzT2YetMK5a0OOoPy/a9BnD1im/0C/MgdR07nqwuie6zOqUNCVxc4O9GPOJj5pssY50y0FhSgPbULZOlSCIDa/5qkjd1+NdiUQ3tlG3rgiZh3/q63LnR0XQ67sn1omLhlFApoxRsLwHyp5fpNwztx8/9rf/fvmOeViKY7IURTlJ0Yy52ug9FLsYgxy+QrMd/H9gyA6Sp/Nnuvkv6FmdZrAb2PKCkeSc6l4HokLVdObLsxR0p7swQ7YPthtAJZZ1oe8dsWp1JcTmXghr76AUoj4S+58UzI=
  - secure: rT3BqVgm/NClBg08gbcyCqGpE8wBc6z7l58vmEtDBGmfEiSzY9zQIm9qY5+sX+hrYhzCWbNmv0A0i1hvsdXU00UExW7/BTi2PiWWiWo4LRr9nHktp8Vo2AOcynr7BcPFeuEgQnMBn5heeZxSGpeVUkw/Lapk5x3IWdCS5lh9llFF5zjfKf+6hDfjIp37YKcXkyBSn5xrVp2VPLvVpUeUqBlroBC/JfIlP9jxqs9pdzscrW2n9wJ8Kyw9Ub2dg7Sm0OkdYpWsO4TEHQK5QmjXCWLlETNdk3+ZkY7dZFyz31UkKkO/lECzDaNsfngTuh5jKiu6MWYu33h4GARhVY1jeH/CPSTDCi9yRlDpRoM6iAYRMbrT5i4nDyslkTxWxs31ZIDq0eepznZi9YjnqmIlzkg6kL8Fu3Cc0YRorevp5QA8ZkwZWNCgbMHjFx0xHwT9kRg2ZL5wcso7Iig4lK09CRBezLiZK0PLnI/l6P7tTLwfGIhIHqVt3+eXtc4hyLBFYJoYsvrR1rfveC4NZL4YePhyRMAhEn2VWkyWjT7TeOCmCIUuWgOhLRte72GFpAv1eIE58Ih8menMwm8JnJA1cT7YlVHKXFz4XSWZbPpp0xraudNUBitftvAEDwWmZ4dMUR3OoARXg+Vs/D3e3VdDqLmFkG2L0Tb45MPIdh3vkXQ=
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_script:
  - gem update --system
  - gem update --remote bundler
script:
  - bundle exec rspec
